name: dartssh2_plus
version: 3.0.0
description: SSH and SFTP client written in pure Dart, aiming to be feature-rich as well as easy to use.
homepage: https://github.com/OpenIoTHub/dartssh2_plus

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  asn1lib: ^1.0.0
  convert: ^3.0.0
  meta: ^1.1.6
  pointycastle: ^3.0.0
  pinenacl: ^0.6.0

dev_dependencies:
  build_runner: ^2.1.1
  dart_code_metrics: ^5.7.6
  lints: ^4.0.0
  test: ^1.6.5

false_secrets:
  - test

analyzer:
  language:
    enableSuperMixins: true
